### ISSUE TITLE
WebSocket ping-pong test case fails intermittently 

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/tools-distribution#203]
Fails with the below error:
```
testPingPongSupport(org.ballerinalang.test.service.websocket.sample.WebSocketPassThroughTestCase)  Time elapsed: 0.409 sec  <<< FAILURE!
java.lang.AssertionError: expected [remote_server_ping] but found [null]
	at org.ballerinalang.test.service.websocket.sample.WebSocketPassThroughTestCase.testPingPongSupport(WebSocketPassThroughTestCase.java:104)
```

**Comment by SupunS** [comment]
Observed another one:
```
testRemoteConnectionClosureFromBallerina(org.ballerinalang.test.service.websocket.sample.WebSocketPassThroughTestCase)  Time elapsed: 0.108 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.ballerinalang.test.service.websocket.sample.WebSocketPassThroughTestCase.testRemoteConnectionClosureFromBallerina(WebSocketPassThroughTestCase.java:133)
```

**Comment by irunika** [comment]
@SupunS will look into it ASAP.
